CREATE TABLE [dbo].[AUStream]
(
	[AUStreamID] NCHAR NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    [URL] NVARCHAR(100) NULL, 
    [Username] NVARCHAR(50) NULL, 
    [Password] NVARCHAR(50) NULL,
	CONSTRAINT [PK_AUStream] PRIMARY KEY CLUSTERED ([AUStreamID] ASC)
)
